# Generated by Django 5.2.7 on 2025-11-27 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_customuser_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_pro_member',
            field=models.BooleanField(default=False),
        ),
    ]
