# Generated by Django 5.2.7 on 2025-12-01 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_customuser_is_pro_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='testresult',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='testresult',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='testresult',
            name='time_remaining',
            field=models.IntegerField(default=0, help_text='Time remaining in seconds'),
        ),
    ]
