# Generated by Django 5.2.7 on 2025-12-03 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testresult_is_completed_testresult_last_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
    ]
