# Generated by Django 5.2.7 on 2025-12-11 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_test_is_free'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneOTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('otp', models.CharField(max_length=6)),
                ('count', models.IntegerField(default=0, help_text='Number of OTP sent')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
