# Generated by Django 5.2.7 on 2025-12-13 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_phoneotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tier-1, Prelims', max_length=100)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order to display tabs (1, 2, 3)')),
                ('test_series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='core.testseries')),
            ],
        ),
        migrations.AddField(
            model_name='test',
            name='stage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='core.teststage'),
        ),
    ]
