# Generated by Django 5.2.7 on 2025-12-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_teststage_test_stage'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='pro_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
