# Generated by Django 5.2.7 on 2025-12-23 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrentAffair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(help_text='Short description for the card')),
                ('content', models.TextField(help_text='Full detail for the detail view')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('source_name', models.CharField(default='PIB', max_length=100)),
                ('source_link', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('NAT', 'National'), ('INT', 'International'), ('ECO', 'Economy'), ('SPT', 'Sports'), ('SCI', 'Science & Tech')], max_length=3)),
                ('is_hot_topic', models.BooleanField(default=False, help_text='Show in Hero Section')),
                ('tags', models.CharField(help_text='Comma separated tags e.g. #G20, #ISRO', max_length=255)),
                ('date', models.DateField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_published', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
