# Generated by Django 5.2.7 on 2025-12-25 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_currentaffair'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Explanation (Hindi)'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_a_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option A (Hindi)'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_b_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option B (Hindi)'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_c_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option C (Hindi)'),
        ),
        migrations.AddField(
            model_name='question',
            name='option_d_hi',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Option D (Hindi)'),
        ),
        migrations.AddField(
            model_name='question',
            name='question_text_hi',
            field=models.TextField(blank=True, null=True, verbose_name='Question (Hindi)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Explanation (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_a',
            field=models.CharField(max_length=255, verbose_name='Option A (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_b',
            field=models.CharField(max_length=255, verbose_name='Option B (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_c',
            field=models.CharField(max_length=255, verbose_name='Option C (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='option_d',
            field=models.CharField(max_length=255, verbose_name='Option D (English)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_text',
            field=models.TextField(verbose_name='Question (English)'),
        ),
    ]
