# Generated by Django 5.2.7 on 2025-12-25 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_question_explanation_hi_question_option_a_hi_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_published',
            field=models.BooleanField(default=False, help_text='Check this ONLY when questions are added'),
        ),
    ]
