"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import dj_database_url
import os
# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-u&qul5=0*%dezdrv+qb0ggba8p8=6lg(-qk((fa$kz-wp=3j4l'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['test-backend-qb46.onrender.com', "localhost", "127.0.0.1"]

CSRF_TRUSTED_ORIGINS = [
    "https://web-production-dee92.up.railway.app","https://examprepare.netlify.app"
]
# Application definition

INSTALLED_APPS = [
    'import_export',
    'django.contrib.sites',
    'allauth.account', 
    'allauth.socialaccount',  # <-- This one creates "Social applications"
    'allauth.socialaccount.providers.google',
    'allauth',
    'corsheaders',
    'dj_rest_auth',
    'dj_rest_auth.registration',
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'core',
    'rest_framework',
    'rest_framework_simplejwt'
]
SITE_ID = 1
AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'SCOPE': [
            'profile',
            'email',
        ],
        'AUTH_PARAMS': {
            'access_type': 'online',
        }
    }
}



MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware', # <-- Kept this one
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware', # <-- Kept this one
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'allauth.account.middleware.AccountMiddleware', # <-- allauth's middleware
]

ROOT_URLCONF = 'backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
from datetime import timedelta

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=5),  # ⏰ Access token expires after 1 minute
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),    # Refresh token lasts 7 days
    "ROTATE_REFRESH_TOKENS": False,                  # (optional) rotates refresh token on every refresh
    "BLACKLIST_AFTER_ROTATION": False,               # blacklists old refresh tokens
    "ALGORITHM": "HS256",
    "SIGNING_KEY": SECRET_KEY,
    "AUTH_HEADER_TYPES": ("Bearer",),
}

WSGI_APPLICATION = 'backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# backend/settings.py

if 'DATABASE_URL' in os.environ:
    # This is the "Production Kitchen" (Render.com)
    # It will use the DATABASE_URL environment variable.
    DATABASES = {
        'default': dj_database_url.parse(os.environ.get('DATABASE_URL'))
    }
else:
    # This is the "Home Kitchen" (Your local machine)
    # It will use the simple db.sqlite3 file.
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
REST_AUTH = {
    'USE_JWT': True,
    'JWT_AUTH_COOKIE': None,
    'JWT_AUTH_REFRESH_COOKIE': None,
    'TOKEN_MODEL': None,
        'REGISTER_SERIALIZER': 'core.serializers.CustomRegisterSerializer',

}

JAZZMIN_SETTINGS = {
      "order_with_respect_to": [
        # Top-level concepts first
        "core.ExamName", 
        "core.TestSeries",
        
        # The main test structure
        "core.Test",
        "core.Section",
        "core.Question",

        # Keep auth models grouped together
        "auth.User",
        "auth.Group",
    ],
    # Title on the login screen (can be full name of your site)
    "site_title": "Test Series Admin",

    # Title on the brand (logo) bar (can be static text or an image)
    "site_header": "TestSeries",

    # Logo to use for your site, must be present in static files
    "site_logo": None, # Or "path/to/your/logo.png"

    # Welcome text on the login screen
    "welcome_sign": "Welcome to the Test Series Admin Panel",

    # Copyright on the footer
    "copyright": "TestSeries Ltd.",
}

CORS_ALLOWED_ORIGINS = [
    "http://localhost:4200",
    "http://127.0.0.1:4200","https://examprepare.netlify.app"
]

STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'
AUTH_USER_MODEL = 'core.CustomUser'
# This tells allauth to skip that confirmation page and redirect directly to Google.
SOCIALACCOUNT_LOGIN_ON_GET = True
ACCOUNT_USER_MODEL_USERNAME_FIELD = None
RAZORPAY_KEY_ID = os.environ.get('RAZORPAY_KEY_ID')
RAZORPAY_KEY_SECRET = os.environ.get('RAZORPAY_KEY_SECRET')
# Add this at the bottom of settings.py
IMPORT_EXPORT_IMPORT_PERMISSION_CODE = 'view' # Optional permissions
IMPORT_EXPORT_USE_TRANSACTIONS = True
IMPORT_EXPORT_SKIP_ADMIN_LOG = False
IMPORT_EXPORT_TMP_STORAGE_CLASS = 'import_export.tmp_storages.MediaStorage'



# core/settings.py

# 1. Basic Verification Settings (Keep these)
ACCOUNT_EMAIL_VERIFICATION = 'mandatory'
ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_CONFIRM_EMAIL_ON_GET = True
ACCOUNT_USERNAME_REQUIRED = False
ACCOUNT_AUTHENTICATION_METHOD = 'email'
# 2. Email Backend Configuration (Brevo SMTP)
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp-relay.brevo.com'
EMAIL_PORT = 2525
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'chinmaykulshreshtha@gmail.com' # Your Login Email
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '') # Defaults to empty string if missing# 3. Default Sender
# This MUST match a "Verified Sender" in your Brevo dashboard
DEFAULT_FROM_EMAIL = 'PrepMaster Team <chinmaykulshreshtha@gmail.com>'